"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Users,Search,Download,Heart,GitBranch,Trash2,ZoomIn,ZoomOut,RotateCcw,UserRound,Save,Edit3,X,Calendar,MapPin,Link2,Unlink} from "lucide-react";
type Gender="Female"|"Male"|"Other"|"Not specified"; type RelationKind="parent"|"partner";
type Person={id:number;name:string;gender?:Gender;birthDate?:string;birthPlace?:string;photo?:string};
type Relation={id:number;from:number;to:number;kind:RelationKind;parentType?:"biological"|"adoptive"};
const root:Person={id:1,name:"You",gender:"Not specified"};
export default function Home(){
const [people,setPeople]=useState<Person[]>([root]),[relations,setRelations]=useState<Relation[]>([]),[selected,setSelected]=useState(1),[name,setName]=useState(""),[query,setQuery]=useState(""),[zoom,setZoom]=useState(1),[editing,setEditing]=useState(false);
useEffect(()=>{const s=localStorage.getItem("fmb-tree-v3");if(s)try{const d=JSON.parse(s);setPeople(d.people||[root]);setRelations(d.relations||[])}catch{}},[]);useEffect(()=>localStorage.setItem("fmb-tree-v3",JSON.stringify({people,relations})),[people,relations]);
const current=people.find(p=>p.id===selected)||root;
const related=(a:number,b:number,kind:RelationKind)=>relations.some(r=>r.kind===kind&&((r.from===a&&r.to===b)||(kind==="partner"&&r.from===b&&r.to===a)));
const create=(kind:"person"|"parent"|"child"|"partner")=>{const id=Date.now();const person={id,name:name.trim()||"New family member",gender:"Not specified" as Gender};setPeople(p=>[...p,person]);if(kind==="parent")setRelations(r=>[...r,{id:id+1,from:id,to:selected,kind:"parent",parentType:"biological"}]);if(kind==="child")setRelations(r=>[...r,{id:id+1,from:selected,to:id,kind:"parent",parentType:"biological"}]);if(kind==="partner")setRelations(r=>[...r,{id:id+1,from:selected,to:id,kind:"partner"}]);setSelected(id);setName("")};
const addSibling=()=>{const parents=relations.filter(r=>r.kind==="parent"&&r.to===selected);const id=Date.now();setPeople(p=>[...p,{id,name:name.trim()||"New sibling",gender:"Not specified"}]);setRelations(r=>[...r,...parents.map((x,i)=>({id:id+i+1,from:x.from,to:id,kind:"parent" as RelationKind,parentType:x.parentType}))]);setSelected(id);setName("")};
const removePerson=(id:number)=>{if(id===1)return;setPeople(p=>p.filter(x=>x.id!==id));setRelations(r=>r.filter(x=>x.from!==id&&x.to!==id));setSelected(1)};
const update=(changes:Partial<Person>)=>setPeople(p=>p.map(x=>x.id===selected?{...x,...changes}:x));
const visible=useMemo(()=>people.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())),[people,query]);
const childrenOf=(id:number)=>relations.filter(r=>r.kind==="parent"&&r.from===id).map(r=>r.to);
const parentsOf=(id:number)=>relations.filter(r=>r.kind==="parent"&&r.to===id).map(r=>r.from);
const siblingsOf=(id:number)=>{const ps=new Set(parentsOf(id));return people.filter(p=>p.id!==id&&parentsOf(p.id).some(x=>ps.has(x))).map(p=>p.id)};
const pos=(p:Person)=>{if(p.id===1)return{x:450,y:260};const parents=parentsOf(p.id),children=childrenOf(1),siblings=siblingsOf(1),partners=relations.filter(r=>r.kind==="partner"&&(r.from===1||r.to===1)).map(r=>r.from===1?r.to:r.from);if(parents.includes(1))return{x:250+children.indexOf(p.id)*190,y:430};if(children.includes(p.id))return{x:250+children.indexOf(p.id)*190,y:430};if(siblings.includes(p.id))return{x:200+siblings.indexOf(p.id)*180,y:260};if(parentsOf(1).includes(p.id))return{x:300+parentsOf(1).indexOf(p.id)*280,y:90};if(partners.includes(p.id))return{x:650+partners.indexOf(p.id)*170,y:260};return{x:450+((p.id%4)-2)*160,y:520};
return <main><nav><a className="brand" href="/">FamilyMapBuilder</a><div><a href="#how">How it works</a><a href="#features">Features</a><a href="#builder" className="navcta">Start building</a></div></nav>
<section className="hero"><div><p className="eyebrow">FREE ONLINE FAMILY TREE BUILDER</p><h1>Build your family tree without complicated software.</h1><p>Create a visual family map in minutes. Add real parent and partner relationships and grow your family map naturally.</p><a className="primary" href="#builder">Start your family tree <GitBranch size={18}/></a><small>Private browser saving included. No account required to start.</small></div><aside><Users size={44}/><h2>Start with one person</h2><p>Your family map grows naturally as you add relationships.</p></aside></section>
<section id="builder" className="builder"><header><div><p className="eyebrow">INTERACTIVE FAMILY MAP</p><h2>Build your tree</h2></div><div className="canvas-actions"><button onClick={()=>setZoom(z=>Math.min(1.35,z+.1))}><ZoomIn size={17}/></button><button onClick={()=>setZoom(z=>Math.max(.65,z-.1))}><ZoomOut size={17}/></button><button onClick={()=>{setPeople([root]);setRelations([]);setSelected(1);setZoom(1)}}><RotateCcw size={17}/></button><button disabled><Download size={17}/> Export soon</button></div></header>
<div className="selected"><UserRound size={18}/><span>Selected: <strong>{current.name}</strong></span><button onClick={()=>setEditing(true)} className="edit-person"><Edit3 size={15}/> Edit profile</button><Save size={16}/><small>Saved automatically on this device</small></div>
<div className="controls"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Family member name"/><button className="primary" onClick={()=>create("person")}><Plus size={18}/> Add unlinked person</button></div><div className="relationships"><button onClick={()=>create("parent")}>Add parent</button><button onClick={addSibling}>Add sibling</button><button onClick={()=>create("partner")}>Add partner</button><button onClick={()=>create("child")}>Add child</button></div>
<div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search family members"/></div>
<div className="tree-viewport"><div className="tree-stage graph-stage" style={{transform:"scale("+zoom+")"}}><svg className="connections" width="900" height="620">{relations.filter(r=>visible.some(p=>p.id===r.from)&&visible.some(p=>p.id===r.to)).map(r=>{const a=pos(people.find(p=>p.id===r.from)!),b=pos(people.find(p=>p.id===r.to)!);return <line key={r.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={r.kind==="partner"?"#758391":"#b8c3cc"} strokeWidth={r.kind==="partner"?"4":"2"} strokeDasharray={r.kind==="partner"?"8 5":undefined}/>})}</svg>{visible.map(p=>{const q=pos(p);return <article style={{left:q.x-82,top:q.y-65}} className={"person graph-person "+(selected===p.id?"active":"")} key={p.id} onClick={()=>setSelected(p.id)}>{p.photo?<img className="avatar photo" src={p.photo} alt=""/>:<div className="avatar">{p.name[0]?.toUpperCase()}</div>}<strong>{p.name}</strong><span>{p.birthDate?p.birthDate.slice(0,4):"Family member"}</span>{p.id!==1&&<button onClick={e=>{e.stopPropagation();removePerson(p.id)}} aria-label={"Remove "+p.name}><Trash2 size={15}/></button>}</article>})}</div></div><p className="tip"><Heart size={17}/> Solid lines show parent-child relationships. Dashed lines show partners.</p></section>
<section id="features" className="features"><article><Link2 size={26}/><h3>Real relationships</h3><p>Parent-child and partner relationships are stored separately from person profiles.</p></article><article><Users size={26}/><h3>Automatic siblings</h3><p>Siblings share the parents of the selected person.</p></article><article><Save size={26}/><h3>Private auto-save</h3><p>Your current family map stays saved in this browser.</p></article></section>
<section id="how" className="how"><p className="eyebrow">HOW IT WORKS</p><h2>Three simple steps</h2><ol><li><b>1</b><span><strong>Start with yourself</strong><br/>Create the first person in your family map.</span></li><li><b>2</b><span><strong>Connect relatives</strong><br/>Add real parent, child and partner relationships.</span></li><li><b>3</b><span><strong>Grow the story</strong><br/>Relationships are preserved separately as your tree grows.</span></li></ol></section><footer>© 2026 FamilyMapBuilder · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></footer>
{editing&&<div className="modal-backdrop" onClick={()=>setEditing(false)}><section className="profile-modal" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">PERSON PROFILE</p><h2>Edit {current.name}</h2></div><button onClick={()=>setEditing(false)}><X/></button></header><label>Name<input value={current.name} onChange={e=>update({name:e.target.value})}/></label><label>Gender<select value={current.gender||"Not specified"} onChange={e=>update({gender:e.target.value as Gender})}><option>Not specified</option><option>Female</option><option>Male</option><option>Other</option></select></label><label><Calendar size={16}/> Date of birth<input type="date" value={current.birthDate||""} onChange={e=>update({birthDate:e.target.value})}/></label><label><MapPin size={16}/> Place of birth<input value={current.birthPlace||""} onChange={e=>update({birthPlace:e.target.value})}/></label><label>Profile photo URL<input type="url" placeholder="https://..." value={current.photo||""} onChange={e=>update({photo:e.target.value})}/></label><button className="primary save-profile" onClick={()=>setEditing(false)}>Save profile</button></section></div>}</main>}